name: Java CI with Maven - selenium tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean compile --file pom.xml

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Test with selenium
        run: mvn test allure:report --file pom.xml
        with:
          allure_results: ./target/allure-results
          allure_history: allure-history
          keep_reports: 5

    report:

      runs-on: ubuntu-latest

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          allure_report: allure-report
          allure_history: allure-history